### ISSUE TITLE
iso reader truncate filenames 

### ISSUE THREAD

**Issue by MalloZup** [hooklift/iso9660#3]
Hi all,

Currently we have an issue with the isoRreader, namely that the filenames are truncated.
Is this a known issue?  I just jumped in the codebase and discovered it.

You can see it here:

https://github.com/dmacvicar/terraform-provider-libvirt/blob/1ea8759eb2b48238e7c2971abeb5bf649bc0c78e/libvirt/cloudinit_def.go#L233

as workaround we do following:
https://github.com/dmacvicar/terraform-provider-libvirt/blob/1ea8759eb2b48238e7c2971abeb5bf649bc0c78e/libvirt/cloudinit_def.go#L251

From my side i will dive and research more in this issue

For any info feel free to ping me and thanks for this Project! :heart:

**Comment by c4milo** [comment]
https://github.com/hooklift/iso9660/blob/master/README.md#not-supported

**Comment by c4milo** [comment]
Joliet extensions are unfortunately not supported, this is why you see the file names truncated

**Comment by MalloZup** [comment]
Ciao @c4milo would be feasible and on the roadmap  to add this support on the project? I could spend a PR for adding this support with your guidance. Thx for your answer

**Comment by MalloZup** [comment]
https://en.wikipedia.org/wiki/ISO_9660#Limitations

**Comment by MalloZup** [comment]
@c4milo i closed because sofar i understood this is a limitation of the ISO_9660 format
